
[colors]
draw_bold_text_with_bright_colors = false

[font.offset]
x = 1
y = 3

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "full"
dimensions = { columns = 100, lines = 25 }

[window.padding]
x = 6
y = 6

[general]
import = [
  "~/.config/alacritty/alacritty-local.toml",
  "~/.config/alacritty/themes/my-theme.toml"
]

[terminal]
