import = ["~/.config/alacritty/alacritty-local.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[[colors.indexed_colors]]
color = "#d18616"
index = 16

[[colors.indexed_colors]]
color = "#cb2431"
index = 17

[colors.bright]
black = "#959da5"
blue = "#005cc5"
cyan = "#3192aa"
green = "#22863a"
magenta = "#5a32a3"
red = "#cb2431"
white = "#d1d5da"
yellow = "#b08800"

[colors.normal]
black = "#24292e"
blue = "#3d507b"
cyan = "#0598bc"
green = "#28a745"
magenta = "#724d8d"
red = "#d73a49"
white = "#ffffff"
yellow = "#dbab09"

[colors.primary]
background = "#ffffff"
foreground = "#24292f"

[font.offset]
x = 1
y = 3

[selection]
save_to_clipboard = true

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "full"

[window.padding]
x = 6
y = 6
